### PR TITLE
Updated the development team

### PR DESCRIPTION
**Pull request by ogdans3**
Updated the development team to the current members of the project instead of the OKSE 1.0 members

### CODE REVIEW

**Comment by einhov** [comment]
This should probably go in a separate AUTHORS or CREDITS file?

**Comment by ogdans3** [comment]
And not in the README.md at all?

**Comment by einhov** [comment]
Indeed. The README should contain only vital information for a newcomer to the project.

**Comment by ogdans3** [comment]
Under which folder would you like the AUTHORS to be in? Or the root directory?

Is it not vital for a new person to know that Andreas Weisethaunet has contributed to the project?

**Comment by duvholt** [comment]
The previous development team should also be kept (maybe specify year?).

**Comment by ogdans3** [comment]
oops
wrong button

Great start!

**Comment by duvholt** [comment]
Example: https://github.com/openstack/swift/blob/master/AUTHORS

**Comment by ogdans3** [comment]
What should i call the new team? Core contributors, New Development Team, Development Team (2016), OKSE 2.0 Development Team?

**Pull request closed without merging**
